# Generated by Django 6.0.6 on 2026-07-04 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlybudget',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='month',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_expense_category_per_user'),
        ),
        migrations.AddConstraint(
            model_name='monthlybudget',
            constraint=models.UniqueConstraint(fields=('user', 'month'), name='unique_monthly_budget_per_user'),
        ),
    ]
