# Generated by Django 6.0.6 on 2026-07-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_signupotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('cash', 'Cash')], default='upi', max_length=20),
        ),
    ]
