# Generated by Django 6.0.6 on 2026-07-05 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('shared', 'Shared'), ('household', 'Household')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('household', 'Household')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('cash', 'Cash'), ('bank', 'Bank'), ('card', 'Card'), ('wallet', 'Wallet'), ('other', 'Other')], default='upi', max_length=20),
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_households', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to='expenses.expensecategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to='expenses.household')),
            ],
            options={
                'ordering': ['-month', 'category__name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.household'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('relation_type', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('roommate', 'Roommate'), ('relative', 'Relative'), ('helper', 'Helper'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_people', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PeopleInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('relation_type', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('roommate', 'Roommate'), ('relative', 'Relative'), ('helper', 'Helper'), ('other', 'Other')], default='other', max_length=20)),
                ('token_hash', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_people_invitations', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='expenses.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('removed', 'Removed')], default='active', max_length=20)),
                ('visibility_level', models.CharField(choices=[('shared_only', 'Shared Only'), ('category_summary', 'Category Summary'), ('monthly_summary', 'Monthly Summary'), ('full_household', 'Full Household')], default='shared_only', max_length=30)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='expenses.household')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to='expenses.person')),
            ],
            options={
                'ordering': ['household', 'role', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('settled', 'Settled'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='expenses.expense')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_shares', to=settings.AUTH_USER_MODEL)),
                ('household_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_shares', to='expenses.householdmember')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_shares', to='expenses.person')),
            ],
            options={
                'ordering': ['expense', 'id'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to='expenses.person'),
        ),
        migrations.CreateModel(
            name='RecurringBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('cash', 'Cash'), ('bank', 'Bank'), ('card', 'Card'), ('wallet', 'Wallet'), ('other', 'Other')], default='upi', max_length=20)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('reminder_days_before', models.PositiveSmallIntegerField(default=3)),
                ('auto_create_expense', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensecategory')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bills', to='expenses.household')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('paid', 'Paid'), ('skipped', 'Skipped'), ('overdue', 'Overdue')], default='upcoming', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_occurrences', to='expenses.expense')),
                ('recurring_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='expenses.recurringbill')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('upi', 'UPI'), ('cash', 'Cash'), ('bank', 'Bank'), ('card', 'Card'), ('wallet', 'Wallet'), ('other', 'Other')], default='upi', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_settlements', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='expenses.expense')),
                ('expense_share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='expenses.expenseshare')),
                ('from_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_sent', to='expenses.person')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_sent', to=settings.AUTH_USER_MODEL)),
                ('to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_received', to='expenses.person')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='household',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_household_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='categorybudget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('household__isnull', True)), models.Q(('user__isnull', True), ('household__isnull', False)), _connector='OR'), name='category_budget_exactly_one_scope'),
        ),
        migrations.AddConstraint(
            model_name='categorybudget',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'category', 'month'), name='unique_personal_category_budget'),
        ),
        migrations.AddConstraint(
            model_name='categorybudget',
            constraint=models.UniqueConstraint(condition=models.Q(('household__isnull', False)), fields=('household', 'category', 'month'), name='unique_household_category_budget'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('owner', 'email'), name='unique_person_owner_email'),
        ),
        migrations.AddIndex(
            model_name='peopleinvitation',
            index=models.Index(fields=['email'], name='expenses_pe_email_51a7e9_idx'),
        ),
        migrations.AddIndex(
            model_name='peopleinvitation',
            index=models.Index(fields=['status'], name='expenses_pe_status_63fee3_idx'),
        ),
        migrations.AddIndex(
            model_name='peopleinvitation',
            index=models.Index(fields=['expires_at'], name='expenses_pe_expires_bfa455_idx'),
        ),
        migrations.AddConstraint(
            model_name='peopleinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('invited_by', 'email'), name='unique_pending_people_invitation'),
        ),
        migrations.AddConstraint(
            model_name='householdmember',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('person__isnull', False), _connector='OR'), name='household_member_has_user_or_person'),
        ),
        migrations.AddConstraint(
            model_name='householdmember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('household',), name='unique_household_owner_member'),
        ),
        migrations.AddConstraint(
            model_name='householdmember',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('household', 'user'), name='unique_household_user_member'),
        ),
        migrations.AddConstraint(
            model_name='householdmember',
            constraint=models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('household', 'person'), name='unique_household_person_member'),
        ),
        migrations.AddConstraint(
            model_name='expenseshare',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('person__isnull', False), ('household_member__isnull', False), _connector='OR'), name='expense_share_has_participant'),
        ),
        migrations.AddConstraint(
            model_name='expenseshare',
            constraint=models.CheckConstraint(condition=models.Q(('share_amount__gte', 0)), name='share_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='expenseshare',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='paid_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='expenseshare',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__lte', models.F('share_amount'))), name='paid_amount_lte_share_amount'),
        ),
        migrations.AddConstraint(
            model_name='recurringbill',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('household__isnull', True)), models.Q(('user__isnull', True), ('household__isnull', False)), _connector='OR'), name='recurring_bill_exactly_one_scope'),
        ),
        migrations.AddConstraint(
            model_name='billoccurrence',
            constraint=models.UniqueConstraint(fields=('recurring_bill', 'due_date'), name='unique_bill_occurrence_due_date'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='settlement_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('from_user__isnull', False), ('from_person__isnull', False), _connector='OR'), name='settlement_has_payer'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('to_user__isnull', False), ('to_person__isnull', False), _connector='OR'), name='settlement_has_receiver'),
        ),
    ]
