# Generated by Django 6.0.6 on 2026-07-05 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_created_by_expense_expense_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='billoccurrence',
            index=models.Index(fields=['due_date', 'status'], name='expenses_bi_due_dat_a249b2_idx'),
        ),
        migrations.AddIndex(
            model_name='billoccurrence',
            index=models.Index(fields=['status', 'due_date'], name='expenses_bi_status_c9218d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'expense_date'], name='expenses_ex_user_id_69fe96_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['household', 'expense_date'], name='expenses_ex_househo_2b5221_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'expense_date'], name='expenses_ex_categor_6b4e94_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['payment_method', 'expense_date'], name='expenses_ex_payment_6db2c2_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_type', 'expense_date'], name='expenses_ex_expense_4677f2_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbill',
            index=models.Index(fields=['user', 'next_due_date'], name='expenses_re_user_id_88d51c_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbill',
            index=models.Index(fields=['household', 'next_due_date'], name='expenses_re_househo_bb6695_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbill',
            index=models.Index(fields=['is_active', 'next_due_date'], name='expenses_re_is_acti_76c3bf_idx'),
        ),
    ]
