# Generated by Django 6.0.6 on 2026-07-10 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


GOAL_RLS_TABLES = [
    "expenses_goal",
    "expenses_goalcontribution",
    "expenses_goalmonthskip",
]


def _goal_rls_sql():
    statements = []
    for table_name in GOAL_RLS_TABLES:
        statements.append(
            f'ALTER TABLE IF EXISTS public."{table_name}" ENABLE ROW LEVEL SECURITY;'
        )
        statements.append(
            f"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = '{table_name}'
    )
    AND NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = '{table_name}'
          AND policyname = 'deny_supabase_api_access'
    ) THEN
        EXECUTE 'CREATE POLICY "deny_supabase_api_access" ON public."{table_name}" FOR ALL TO public USING (false) WITH CHECK (false)';
    END IF;
END $$;
""".strip()
        )
    return "\n".join(statements)


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0008_add_deny_all_rls_policies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("target_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("template_key", models.CharField(blank=True, max_length=50)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "target_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="GoalContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("contribution_date", models.DateField()),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="expenses.goal",
                    ),
                ),
            ],
            options={
                "ordering": ["-contribution_date", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GoalMonthSkip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skipped_months",
                        to="expenses.goal",
                    ),
                ),
            ],
            options={
                "ordering": ["month", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["user", "status", "target_date"],
                name="expenses_go_user_id_f1a005_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["user", "target_date"],
                name="expenses_go_user_id_681787_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_amount__gt", 0)),
                name="goal_target_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "active"), ("completed_at__isnull", True)),
                    models.Q(("status", "completed"), ("completed_at__isnull", False)),
                    _connector="OR",
                ),
                name="goal_completion_state_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="goalcontribution",
            index=models.Index(
                fields=["goal", "contribution_date"],
                name="expenses_go_goal_id_65519f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalcontribution",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="goal_contribution_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalmonthskip",
            constraint=models.UniqueConstraint(
                fields=("goal", "month"),
                name="unique_goal_skipped_month",
            ),
        ),
        migrations.RunSQL(
            sql=_goal_rls_sql(),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
