# Generated by Django 6.0.6 on 2026-07-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_goal_goalcontribution_goalmonthskip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcontribution',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_contributions', to='expenses.expense'),
        ),
    ]
