# Generated by Django 6.0.6 on 2026-07-10 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_goal_contribution_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expensecategory',
            name='unique_expense_category_per_user',
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=10),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=10),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'transaction_type', 'expense_date'], name='expenses_ex_user_id_567f3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'transaction_type'), name='unique_transaction_category_per_user'),
        ),
    ]
