# Generated by Django 6.0.6 on 2026-07-12 19:47

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


LOAN_RLS_TABLES = [
    "expenses_loan",
    "expenses_loanpayment",
]


def _loan_rls_sql():
    statements = []
    for table_name in LOAN_RLS_TABLES:
        statements.append(
            f'ALTER TABLE IF EXISTS public."{table_name}" ENABLE ROW LEVEL SECURITY;'
        )
        statements.append(
            f"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = '{table_name}'
    )
    AND NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = '{table_name}'
          AND policyname = 'deny_supabase_api_access'
    ) THEN
        EXECUTE 'CREATE POLICY "deny_supabase_api_access" ON public."{table_name}" FOR ALL TO public USING (false) WITH CHECK (false)';
    END IF;
END $$;
""".strip()
        )
    return "\n".join(statements)


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_remove_expensecategory_unique_expense_category_per_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('borrowed', 'Borrowed'), ('lent', 'Lent')], max_length=12)),
                ('name', models.CharField(max_length=150)),
                ('counterparty_name', models.CharField(max_length=150)),
                ('loan_type', models.CharField(choices=[('personal', 'Personal'), ('home', 'Home'), ('business', 'Business'), ('vehicle', 'Vehicle'), ('education', 'Education'), ('credit', 'Credit'), ('other', 'Other')], default='personal', max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('annual_interest_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('interest_type', models.CharField(choices=[('none', 'No interest'), ('simple', 'Simple annual interest')], default='none', max_length=12)),
                ('disbursed_date', models.DateField()),
                ('interest_start_date', models.DateField(blank=True, null=True)),
                ('repayment_frequency', models.CharField(choices=[('one_time', 'One time'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='monthly', max_length=16)),
                ('planned_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('account_reference', models.CharField(blank=True, max_length=100)),
                ('collateral_note', models.TextField(blank=True)),
                ('terms_note', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=12)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='expenses.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'next_due_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('cash', 'Cash'), ('bank', 'Bank'), ('card', 'Card'), ('wallet', 'Wallet'), ('other', 'Other')], default='upi', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expenses.loan')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'status', 'next_due_date'], name='expenses_lo_user_id_6e2c00_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'direction', 'status'], name='expenses_lo_user_id_a3e50f_idx'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('principal_amount__gt', 0)), name='loan_principal_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('annual_interest_rate__gte', 0)), name='loan_interest_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('planned_payment_amount__gte', 0)), name='loan_planned_payment_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), ('closed_on__isnull', True)), models.Q(('status', 'closed'), ('closed_on__isnull', False)), _connector='OR'), name='loan_closure_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='loanpayment',
            index=models.Index(fields=['loan', 'payment_date'], name='expenses_lo_loan_id_c806d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='loanpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='loan_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='loanpayment',
            constraint=models.CheckConstraint(condition=models.Q(('principal_amount__gte', 0), ('interest_amount__gte', 0), ('fee_amount__gte', 0)), name='loan_payment_components_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='loanpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('principal_amount'), '+', models.F('interest_amount')), '+', models.F('fee_amount')))), name='loan_payment_components_match_total'),
        ),
        migrations.RunSQL(
            sql=_loan_rls_sql(),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
