# Generated by Django 6.0.6 on 2026-07-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_remove_expensecategory_unique_expense_category_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='goal',
            name='expenses_go_user_id_f1a005_idx',
        ),
        migrations.RemoveIndex(
            model_name='goal',
            name='expenses_go_user_id_681787_idx',
        ),
        migrations.RemoveConstraint(
            model_name='goal',
            name='goal_target_amount_positive',
        ),
        migrations.RemoveConstraint(
            model_name='goal',
            name='goal_completion_state_consistent',
        ),
        migrations.RemoveIndex(
            model_name='goalcontribution',
            name='expenses_go_goal_id_65519f_idx',
        ),
        migrations.RemoveConstraint(
            model_name='goalcontribution',
            name='goal_contribution_amount_positive',
        ),
        migrations.RemoveConstraint(
            model_name='goalmonthskip',
            name='unique_goal_skipped_month',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='goalmonthskip',
            name='goal',
        ),
        migrations.DeleteModel(
            name='GoalContribution',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='GoalMonthSkip',
        ),
    ]
